name: Auto Update

on:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:

      - name: SetUp Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.4
          architecture: x64

      - name: Checkout Resource
        uses: actions/checkout@v2


      - name: Checkout Bot
        uses: actions/checkout@v2
        with: 
          repository: yuanyan3060/Arknights-Bot-Resource-Bot
          path: $GITHUB_WORKSPACE/../Arknights-Bot-Resource-Bot
          token: ${{secrets.PERSONAL_TOKEN}}

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/../Arknights-Bot-Resource-Bot
          python3 -m pip install --upgrade pip
          python3 -m venv venv
          venv/bin/python -m pip install --upgrade pip wheel setuptools
          venv/bin/python -m pip install -r requirements.txt
        shell: bash

      - name: Update
        run: |
          cd $GITHUB_WORKSPACE/../Arknights-Bot-Resource-Bot
          venv/bin/python main.py ../Arknights-Bot-Resource
        shell: bash

          
      - name: cd
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          ls -a 

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'auto update by git action'
          add: '.'